baseURL = "http://example.org/"
languageCode = "en-us"
title = "Sourdough for Busy People"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "The Method"
    url = "/method/"
    weight = 2
  [[menu.main]]
    name = "Recipes"
    url = "/recipes/"
    weight = 3
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4