backend:
  name: git-gateway
  branch: master # Branch to update (main or master)

# Global settings
local_backend: true
publish_mode: editorial_workflow
site_url: https://evasbread.netlify.app/
display_url: https://evasbread.netlify.app/

# Media settings
media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "settings"
    label: "Site Settings"
    files:
      - name: "style"
        label: "Style Variables"
        file: "content/settings/style.json"
        fields:
          - {label: "Primary Color", name: "primaryColor", widget: "color", required: true}
          - {label: "Secondary Color", name: "secondaryColor", widget: "color", required: true}
          - {label: "Button Font Size", name: "buttonFontSize", widget: "string", required: true}
          - {label: "Button Padding", name: "buttonPadding", widget: "string", required: true}
          - {label: "Button Border Radius", name: "buttonBorderRadius", widget: "string", required: true}
          - {label: "Card Background Color", name: "cardBgColor", widget: "color", required: true}
          - {label: "Card Border Radius", name: "cardBorderRadius", widget: "string", required: true}
          - {label: "Card Box Shadow", name: "cardBoxShadow", widget: "string", required: true}
          - {label: "Card Padding", name: "cardPadding", widget: "string", required: true}
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {
              label: "Subheader", 
              name: "subheader", 
              widget: "markdown",
              required: false,
              buttons: [
                "bold", 
                "italic", 
                "link", 
                "heading-two", 
                "heading-three", 
                "quote", 
                "bulleted-list", 
                "numbered-list"
              ]
            }